spring.application.name=member-auth-api
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
app.email.provider=in-memory
app.email.mailjet.api-key=${MAILJET_API_KEY:}
app.email.mailjet.api-secret=${MAILJET_API_SECRET:}
app.email.mailjet.sender-email=${MAILJET_SENDER_EMAIL:}
app.email.mailjet.sender-name=${MAILJET_SENDER_NAME:Member Auth}
app.email.mailjet.activation-base-url=${APP_EMAIL_ACTIVATION_BASE_URL:http://localhost:3000/activate}
app.jwt.issuer=${APP_JWT_ISSUER:http://localhost:8080}
app.jwt.secret=${APP_JWT_SECRET:}
app.jwt.access-token-expires-in=${APP_JWT_ACCESS_TOKEN_EXPIRES_IN:PT1H}
