spring.application.name=member-auth-api
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
app.email.provider=in-memory
app.email.mailjet.api-key=${MAILJET_API_KEY:}
app.email.mailjet.api-secret=${MAILJET_API_SECRET:}
app.email.mailjet.sender-email=${MAILJET_SENDER_EMAIL:}
app.email.mailjet.sender-name=${MAILJET_SENDER_NAME:Member Auth}
app.email.mailjet.activation-base-url=${APP_EMAIL_ACTIVATION_BASE_URL:http://localhost:8080/api/auth/activate}
