CREATE TABLE email_activation_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_email_activation_tokens PRIMARY KEY (id),
    CONSTRAINT fk_email_activation_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_email_activation_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_email_activation_tokens_user_id
    ON email_activation_tokens (user_id);
