CREATE TABLE login_two_factor_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    challenge_id VARCHAR(36) NOT NULL,
    code_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    verified_at TIMESTAMP WITH TIME ZONE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_login_two_factor_codes PRIMARY KEY (id),
    CONSTRAINT fk_login_two_factor_codes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_login_two_factor_codes_challenge_id UNIQUE (challenge_id),
    CONSTRAINT ck_login_two_factor_codes_failed_attempts CHECK (failed_attempts >= 0)
);

CREATE INDEX idx_login_two_factor_codes_user_id
    ON login_two_factor_codes (user_id);

CREATE INDEX idx_login_two_factor_codes_user_created_at
    ON login_two_factor_codes (user_id, created_at);
